-- SCRIPT DE NETTOYAGE DES DONNÉES
-- Vide toutes les tables pour permettre une exécution propre du scénario de test

TRUNCATE TABLE 
    notifications,
    tracking_events,
    tracking_links,
    transactions, 
    kyc_verifications, 
    campaign_influencers, 
    campaigns, 
    leads, 
    trust_scores, 
    payment_accounts, 
    payout_preferences, 
    invoices, 
    webhook_logs, 
    webhooks, 
    api_keys, 
    rate_limits, 
    data_exports, 
    security_events, 
    promotions, 
    commercial_objectives, 
    referral_codes, 
    live_streams, 
    user_badges, 
    disputes, 
    workspace_comments, 
    workspace_members, 
    workspaces, 
    integration_sync_logs, 
    integrations, 
    social_media_accounts, 
    social_media_publications,
    product_reviews,
    qr_scan_events, 
    nfc_tap_events, 
    offline_actions, 
    report_runs, 
    custom_reports, 
    content_templates, 
    media_library, 
    seo_metadata, 
    user_2fa, 
    user_sessions, 
    sales_assignments, 
    affiliation_requests, 
    analytics_reports, 
    support_tickets, 
    payment_integrations, 
    subscriptions, 
    email_campaigns, 
    sms_campaigns, 
    product_collections, 
    wishlists, 
    shipments, 
    warehouses, 
    coupons, 
    conversations, 
    events
CASCADE;

-- Optionnel : Supprimer les utilisateurs de test s'ils existent encore
DELETE FROM users WHERE email IN (
    'admin@getyourshare.com',
    'influenceur@test.com',
    'influenceur2@test.com',
    'marchand@test.com',
    'commercial@test.com'
);
