[build]
builder = "NIXPACKS"

[phases.setup]
nixPkgs = ["python311", "postgresql"]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt --no-cache-dir"
]

[phases.build]
cmds = [
  "python -m compileall ."
]

[start]
cmd = "python run.py"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
