-- PARTIE 1 : AJOUT DES COLONNES MANQUANTES
-- Exécutez ce bloc en premier

ALTER TABLE products ADD COLUMN IF NOT EXISTS low_stock_alert BOOLEAN DEFAULT FALSE;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS quality_score INTEGER DEFAULT 0;
ALTER TABLE trust_scores ADD COLUMN IF NOT EXISTS refund_rate DECIMAL(5,2) DEFAULT 0;
ALTER TABLE payment_accounts ADD COLUMN IF NOT EXISTS account_id VARCHAR(255);
ALTER TABLE qr_scan_events ADD COLUMN IF NOT EXISTS scan_method VARCHAR(50);
ALTER TABLE integrations ADD COLUMN IF NOT EXISTS status VARCHAR(50) DEFAULT 'active';
ALTER TABLE custom_reports ALTER COLUMN type DROP NOT NULL;
ALTER TABLE content_templates ALTER COLUMN id SET DEFAULT gen_random_uuid();
